apiVersion: apps/v1
kind: Deployment
metadata: { name: postgres, namespace: payment-poc }
spec:
  replicas: 1
  selector: { matchLabels: { app: postgres } }
  template:
    metadata: { labels: { app: postgres } }
    spec:
      containers:
        - name: postgres
          image: postgres:18-alpine
          ports: [{ containerPort: 5432 }]
          env:
            - { name: POSTGRES_DB, value: payments }
            - { name: POSTGRES_USER, value: payments }
            - { name: POSTGRES_PASSWORD, value: payments }
---
apiVersion: v1
kind: Service
metadata: { name: postgres, namespace: payment-poc }
spec:
  selector: { app: postgres }
  ports: [{ port: 5432, targetPort: 5432 }]
