apiVersion: apps/v1
kind: Deployment
metadata: { name: redpanda, namespace: payment-poc }
spec:
  replicas: 1
  selector: { matchLabels: { app: redpanda } }
  template:
    metadata: { labels: { app: redpanda } }
    spec:
      containers:
        - name: redpanda
          image: redpandadata/redpanda:latest
          args: ["redpanda","start","--overprovisioned","--smp=1","--memory=512M","--reserve-memory=0M","--node-id=0","--check=false","--kafka-addr=PLAINTEXT://0.0.0.0:9092","--advertise-kafka-addr=PLAINTEXT://redpanda:9092"]
          ports: [{ containerPort: 9092 }]
---
apiVersion: v1
kind: Service
metadata: { name: redpanda, namespace: payment-poc }
spec:
  selector: { app: redpanda }
  ports: [{ port: 9092, targetPort: 9092 }]
